--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      UNAM
-- Project :      bancaria1.DM1
-- Author :       galigaribaldi@live.com
--
-- Date Created : Friday, March 06, 2020 17:47:30
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: CUENTA_BANCARIA 
--

CREATE TABLE CUENTA_BANCARIA(
    FECHA_CONSULTA       VARCHAR(40),
    SALDO                VARCHAR(40),
    USUARIO_CUENTA_ID    INT            NOT NULL
)ENGINE=MYISAM
;



-- 
-- TABLE: USUARIO 
--

CREATE TABLE USUARIO(
    USUARIO_ID          INT            NOT NULL,
    EDAD                VARCHAR(40),
    NOMBRE              VARCHAR(40),
    APELLIDO_PATERNO    VARCHAR(40),
    APELLIDO_MATERNO    VARCHAR(40),
    PRIMARY KEY (USUARIO_ID)
)ENGINE=MYISAM
;



-- 
-- TABLE: USUARIO_CUENTA 
--

CREATE TABLE USUARIO_CUENTA(
    USUARIO_CUENTA_ID    INT    NOT NULL,
    USUARIO_ID           INT    NOT NULL,
    PRIMARY KEY (USUARIO_CUENTA_ID)
)ENGINE=MYISAM
;



-- 
-- TABLE: CUENTA_BANCARIA 
--

ALTER TABLE CUENTA_BANCARIA ADD CONSTRAINT RefUSUARIO_CUENTA3 
    FOREIGN KEY (USUARIO_CUENTA_ID)
    REFERENCES USUARIO_CUENTA(USUARIO_CUENTA_ID)
;


-- 
-- TABLE: USUARIO_CUENTA 
--

ALTER TABLE USUARIO_CUENTA ADD CONSTRAINT RefUSUARIO2 
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID)
;


