
CREATE TABLE CUENTA_BANCARIA(
    CUENTA_BANCARIA_ID    DECIMAL(40, 0)    NOT NULL,
    FECHA_CONSULTA        VARCHAR(40)       NOT NULL,
    SALDO                 DECIMAL(40, 0)    NOT NULL,
    ESTADO                VARCHAR(40)       NOT NULL,
    FECHA_APERTURA        VARCHAR(40)       NOT NULL,
    PRIMARY KEY (CUENTA_BANCARIA_ID)
)ENGINE=MYISAM
;   

CREATE TABLE USUARIO(
    USUARIO_ID          DECIMAL(40, 0)    NOT NULL,
    NOMBRE              VARCHAR(40)       NOT NULL,
    APELLIDO_PATERNO    VARCHAR(40)       NOT NULL,
    APELLIDO_MATERNO    VARCHAR(40),
    EDAD                DECIMAL(40, 0)    NOT NULL,
    DIRECCION           VARCHAR(40)       NOT NULL,
    CURP                VARCHAR(40)       NOT NULL,
    TELEFONO            VARCHAR(40)       NOT NULL,
    PRIMARY KEY (USUARIO_ID)
)ENGINE=MYISAM
;

CREATE TABLE USUARIO_CUENTA(
    USUARIO_CUENTA_ID     DECIMAL(40, 0)    NOT NULL,
    USUARIO_ID            DECIMAL(40, 0),
    CUENTA_BANCARIA_ID    DECIMAL(40, 0),
    PRIMARY KEY (USUARIO_CUENTA_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (CUENTA_BANCARIA_ID) REFERENCES CUENTA_BANCARIA(CUENTA_BANCARIA_ID)
)ENGINE=MYISAM
;
